
default: ' '

owner: ' '

admin: ' '

mod: ' '

donator: ' '

donatorplus: ' '

none: ' '

trusted: ' '

donatorking: ' '

leavemessages:
    - Enter leave message here ($ for players name)
joinmessages:
    - Enter join messages here ($ for players name)

